// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3zvXWBDnsoCjG4CP5Ew_FLzxdND11dt4',
    appId: '1:957197321956:web:8f3ea0ed083fcd1b0acef1',
    messagingSenderId: '957197321956',
    projectId: 'island-social-development',
    authDomain: 'island-social-development.firebaseapp.com',
    storageBucket: 'island-social-development.firebasestorage.app',
    measurementId: 'G-BPBF546EHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_HXBnxQz1KfFJh2PFaxAix6fHbN1hWZg',
    appId: '1:957197321956:android:b5c3c21ba31a4ea80acef1',
    messagingSenderId: '957197321956',
    projectId: 'island-social-development',
    storageBucket: 'island-social-development.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-2DUqqu0nORzw2ijWpRRRhs2pzdlG5E8',
    appId: '1:957197321956:ios:dbb6b009be6794a10acef1',
    messagingSenderId: '957197321956',
    projectId: 'island-social-development',
    storageBucket: 'island-social-development.firebasestorage.app',
    iosBundleId: 'com.example.islandSocialDevelopment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-2DUqqu0nORzw2ijWpRRRhs2pzdlG5E8',
    appId: '1:957197321956:ios:dbb6b009be6794a10acef1',
    messagingSenderId: '957197321956',
    projectId: 'island-social-development',
    storageBucket: 'island-social-development.firebasestorage.app',
    iosBundleId: 'com.example.islandSocialDevelopment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3zvXWBDnsoCjG4CP5Ew_FLzxdND11dt4',
    appId: '1:957197321956:web:2fa82e2b4b2465000acef1',
    messagingSenderId: '957197321956',
    projectId: 'island-social-development',
    authDomain: 'island-social-development.firebaseapp.com',
    storageBucket: 'island-social-development.firebasestorage.app',
    measurementId: 'G-TSM042PJDS',
  );
}
