const Map<String, String> ar = {
  'title': 'جزيرة التنمية الاجتماعية',
  'signup': 'قم بانشاء حسابك الان:',
  'username': 'اسم المستخدم',
  'Email Address': 'عنوان البريد الالكتروني',
  'Phone Number': 'رقم الهاتف',
  'age': 'العمر',
  'Password': 'كلمة المرور',
  'signupterm': ' هل لديك حساب بالفعل؟',
  'signupterm2': ' قم بتسجيل الدخول',
  'Register': 'اشتراك',
  'signinterm': 'ليس لديك حساب من قبل؟',
  'signinterm2': ' قم بتسجيل الاشتراك',
  'welcom': 'مرحبا بك من جديد',
  'signin': 'بامكانك تسجيل دخول الأن',
  'signintext': 'تسجيل الدخول',
};
